name: tiket_bioskop

description: Aplikasi Pembelian Tiket Bioskop Online - premium, modern, clean, responsif, clean architecture, Riverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  dio: ^5.4.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  animations: ^2.0.11
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
